workflows:
  ios-native-quick-start:
    name: iOS Native
    max_build_duration: 120  # Keep within the allowed range
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: accesCodeMagic
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.savings.mond
      vars:
        BUNDLE_ID: "com.savings.mond"
        XCODE_PROJECT: "MrBetanoSavings.xcodeproj"
        XCODE_SCHEME: "MrBetanoSavings"
        APP_STORE_APPLE_ID: 6737456175
      xcode: 15.3
       
    scripts:
      - name: Increment build number
        script: |
          cd $CM_BUILD_DIR
          LATEST_BUILD_NUMBER=$(app-store-connect get-latest-app-store-build-number "$APP_STORE_APPLE_ID")
          agvtool new-version -all $(($LATEST_BUILD_NUMBER + 1))
      - name: Build ipa for distribution
        script: |
          xcode-project build-ipa \
            --project "$CM_BUILD_DIR/MrBetanoSavings.xcodeproj" \
            --scheme "MrBetanoSavings" \
            --export-options-plist "$CM_BUILD_DIR/export_options.plist"    
    artifacts:
      - "$CM_BUILD_DIR/MrBetanoSavings.ipa"  # Path to the built .ipa file
    
    publishing:
      email:
        recipients:
          - nicu161299@gmail.com
          - user_2@example.com
        notify:
          success: true
          failure: true  # Set to true if you want notifications for failures
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: QN9Q977H42
        issuer_id: 27172b6f-4ac4-4aa8-bdda-5bdfd61bef86
        submit_to_testflight: true
        beta_groups:
          - "Actual Beta Group Name 1"  # Replace with actual group names
          - "Actual Beta Group Name 2"
        submit_to_app_store: true
